# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2869d48fb4985c8c0667f042d75aa48d8d374f06c5e976a8aaf7741b6385173d53127de92629acd2a59b05a38f840c5d33a8a1c9e0205856054e3768366a76b2

test:
  secret_key_base: f992f7f5fc91ab0e01ed25e2670f54f7819cc4c3873ae354dde5921a5c14c1d68822701b33eecea520e5223a8de799fe8f32835878a9c6fbf9ff03dfb1770d3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
